services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920 # HTTPS (optional)
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      # Disco externo Movixy
      - /Volumes/Movixy/movies:/media/movies:ro
      - /Volumes/Movixy/Series:/media/series:ro
    restart: 'unless-stopped'
